#!/bin/sh

In_Version_Range() {
   lower="$1"
   ver="$2"
   upper="$3"
   [ "$ver" ] || return 1
   [ "$ver" != "$lower" -a "$(GuessLatest "$ver" "$lower")" = "$lower" ] && return 1
   [ "$upper" ] || return 0
   [ "$(GuessLatest "$ver" "$upper")" = "$upper" ] || return 1
   [ "$ver" = "$upper" -a "$ver" != "$lower" ] && return 1
   return 0
}

Symlink_Aliens() {
   targetdir="$1"
   shift
   find "$@" -mindepth 1 | while read entry
   do
      local bname="${entry##*/}"
      local targetfile="$targetdir/$bname"
      if [[ -L "$targetfile" ]]
      then
         local rtarget=$(realpath -e "$targetfile")
         # Only overwrite /System/Aliens symlinks
         if [[ "$rtarget" =~ ^"$goboSystem/Aliens" ]]
         then
            rm -f "$targetfile"
         else
            continue
         fi
      fi
      ln -ns "$entry" "$targetfile"
   done
}

Cleanup_Aliens() {
   find "$goboExecutables" | RemoveBroken
}
